server:
  error:
    include-message: always

logging:
  level:
    root: warn
    com.zuehlke.database: debug

spring:
  profiles:
    active: test
  datasource:
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update