server:
  error:
    include-message: always

logging:
  level:
    root: warn
    com.zuehlke.database: debug

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/releases
    username: root
    password: my-secret-pw

  jpa:
    hibernate:
      ddl-auto: create