name: Test CI

# This CI file is used just for the initial presentation of the CI/CD on GitHub.
# It will just run docker hello-world to display most basic possibilities.

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      # Here we check out our repo
      - uses: actions/checkout@v3

      # Here we enable usage of docker as a tool
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Here we run the base hello-world docker container
      - name: Run docker hello-world
        run: docker run hello-world